// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/github/[username].tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/weather/[type].tsx";
import * as $5 from "./routes/weather/index.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/github/[username].tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/weather/[type].tsx": $4,
    "./routes/weather/index.tsx": $5,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
