// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/weather/[type].tsx";
import * as $4 from "./routes/weather/index.tsx";
import * as $$0 from "./islands/NavPanel.tsx";
import * as $$1 from "./islands/Router.tsx";
import * as $$2 from "./islands/ScreenSize.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/weather/[type].tsx": $3,
    "./routes/weather/index.tsx": $4,
  },
  islands: {
    "./islands/NavPanel.tsx": $$0,
    "./islands/Router.tsx": $$1,
    "./islands/ScreenSize.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
